version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bootcamp_final_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  stock-data-app:
    build: ./project-stock-data
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  data-provider-app:
    build: ./project-data-provider
    depends_on:
      - stock-data-app
    ports:
      - "8081:8081"

  heatmap-ui:
    build: ./project-heatmap-ui
    depends_on:
      - stock-data-app
    ports:
      - "8102:8102"

volumes:
  pgdata: